### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by KvizadSaderah** [oaguy1/AdventureGPT#2]
there is no requirements.txt file in project, so how do i run command for it?

`python -m pip install -r requirements.txt`

**Comment by oaguy1** [comment]
@KvizadSaderah so reasonable! I just added one. Sorry for the oversight. It’s written in Python 3.11, so the requirements might reflect that. The following pip install should get you similar results on older versions of Python.

```bash
pip install openai adventure
```
